<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>MdbConverter.Access</RootNamespace>
    <AssemblyName>MdbConverter.Access</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MdbConverter.Core\MdbConverter.Core.csproj" />
    <PackageReference Include="System.Data.OleDb" Version="8.0.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>
</Project>
