using System.Globalization;
using System.Text;
using MdbConverter.Core.Models;

namespace MdbConverter.Core.Postgres;

public sealed class PostgresSqlWriter : IDisposable
{
    public const int DefaultBatchSize = 200;
    private const string CreatedTable = "_mdb_created";

    private readonly TextWriter _writer;
    private readonly ConflictMode _mode;
    private readonly int _batchSize;
    private bool _headerWritten;

    public PostgresSqlWriter(TextWriter writer, ConflictMode mode, int batchSize = DefaultBatchSize)
    {
        _writer = writer;
        _mode = mode;
        _batchSize = batchSize > 0 ? batchSize : DefaultBatchSize;
    }

    public void WriteHeader()
    {
        if (_headerWritten)
        {
            return;
        }

        _writer.WriteLine("-- Generated by MDB Converter. Offline script. Apply with psql.");
        _writer.WriteLine("SET client_encoding = 'UTF8';");
        _writer.WriteLine("SET standard_conforming_strings = on;");
        _writer.WriteLine();

        if (_mode == ConflictMode.Skip)
        {
            _writer.WriteLine($"CREATE TEMP TABLE IF NOT EXISTS {CreatedTable} (name text PRIMARY KEY);");
            _writer.WriteLine();
        }

        _headerWritten = true;
    }

    public void WriteTableDefinition(TableSchema table)
    {
        WriteHeader();
        var quoted = PostgresIdentifier.Quote(table.Name);

        if (_mode == ConflictMode.Replace)
        {
            _writer.WriteLine($"DROP TABLE IF EXISTS {quoted} CASCADE;");
            _writer.WriteLine(BuildCreateTable(table, ifNotExists: false));
            WriteIndexes(table, guarded: false);
        }
        else
        {
            _writer.WriteLine($"INSERT INTO {CreatedTable} (name)");
            _writer.WriteLine($"SELECT {PostgresIdentifier.Literal(table.Name)}");
            _writer.WriteLine($"WHERE to_regclass(format('%I.%I', current_schema(), {PostgresIdentifier.Literal(table.Name)})) IS NULL");
            _writer.WriteLine("ON CONFLICT DO NOTHING;");
            _writer.WriteLine(BuildCreateTable(table, ifNotExists: true));
            WriteIndexes(table, guarded: true);
        }

        _writer.WriteLine();
    }

    public void WriteInsertBatch(TableSchema table, IReadOnlyList<IReadOnlyDictionary<string, object?>> rows)
    {
        if (rows.Count == 0 || table.Columns.Count == 0)
        {
            return;
        }

        var quotedTable = PostgresIdentifier.Quote(table.Name);
        var quotedColumns = string.Join(", ", table.Columns.Select(c => PostgresIdentifier.Quote(c.Name)));
        var selectColumns = string.Join(", ", table.Columns.Select(c => "v." + PostgresIdentifier.Quote(c.Name)));
        var valueRows = new List<string>(rows.Count);

        foreach (var row in rows)
        {
            var cells = table.Columns.Select(column =>
            {
                row.TryGetValue(column.Name, out var value);
                var literal = PostgresLiteral.Format(value, column.PostgresType);
                return literal + "::" + CastType(column);
            });
            valueRows.Add("  (" + string.Join(", ", cells) + ")");
        }

        var valuesSql = string.Join("," + Environment.NewLine, valueRows);
        var aliasColumns = string.Join(", ", table.Columns.Select(c => PostgresIdentifier.Quote(c.Name)));

        if (_mode == ConflictMode.Replace)
        {
            _writer.WriteLine($"INSERT INTO {quotedTable} ({quotedColumns}) VALUES");
            _writer.WriteLine(valuesSql + ";");
        }
        else
        {
            _writer.WriteLine($"INSERT INTO {quotedTable} ({quotedColumns})");
            _writer.WriteLine($"SELECT {selectColumns}");
            _writer.WriteLine("FROM (VALUES");
            _writer.WriteLine(valuesSql);
            _writer.WriteLine($") AS v({aliasColumns})");
            _writer.WriteLine($"WHERE EXISTS (SELECT 1 FROM {CreatedTable} WHERE name = {PostgresIdentifier.Literal(table.Name)});");
        }

        _writer.WriteLine();
    }

    public void WriteQueriesTable(IReadOnlyList<QuerySchema> queries)
    {
        if (queries.Count == 0)
        {
            return;
        }

        WriteHeader();
        var table = new TableSchema
        {
            Name = "access_queries",
            Columns =
            [
                new ColumnSchema
                {
                    Name = "name",
                    AccessTypeName = "Text",
                    OleDbType = 202,
                    PostgresType = "text",
                    AllowNull = false
                },
                new ColumnSchema
                {
                    Name = "sql",
                    AccessTypeName = "Memo",
                    OleDbType = 203,
                    PostgresType = "text",
                    AllowNull = true
                }
            ],
            Indexes = [],
            PrimaryKeyColumns = ["name"]
        };

        WriteTableDefinition(table);
        var chunk = _batchSize;
        for (var i = 0; i < queries.Count; i += chunk)
        {
            var slice = queries.Skip(i).Take(chunk)
                .Select(q => (IReadOnlyDictionary<string, object?>)new Dictionary<string, object?>
                {
                    ["name"] = q.Name,
                    ["sql"] = q.Sql
                })
                .ToList();
            WriteInsertBatch(table, slice);
        }
    }

    public void WriteForeignKeys(IReadOnlyList<ForeignKeySchema> keys, IReadOnlySet<string> selectedTables)
    {
        foreach (var key in keys)
        {
            if (!selectedTables.Contains(key.FromTable) || !selectedTables.Contains(key.ToTable))
            {
                continue;
            }

            var constraint = string.IsNullOrWhiteSpace(key.Name)
                ? $"FK_{key.FromTable}_{key.ToTable}"
                : key.Name;
            var fromCols = string.Join(", ", key.FromColumns.Select(PostgresIdentifier.Quote));
            var toCols = string.Join(", ", key.ToColumns.Select(PostgresIdentifier.Quote));
            var sql =
                $"ALTER TABLE {PostgresIdentifier.Quote(key.FromTable)} ADD CONSTRAINT {PostgresIdentifier.Quote(constraint)} " +
                $"FOREIGN KEY ({fromCols}) REFERENCES {PostgresIdentifier.Quote(key.ToTable)} ({toCols})";

            if (_mode == ConflictMode.Replace)
            {
                _writer.WriteLine(sql + ";");
            }
            else
            {
                _writer.WriteLine("DO $mdb$");
                _writer.WriteLine("BEGIN");
                _writer.WriteLine($"  IF EXISTS (SELECT 1 FROM {CreatedTable} WHERE name = {PostgresIdentifier.Literal(key.FromTable)}) THEN");
                _writer.WriteLine("    BEGIN");
                _writer.WriteLine($"      EXECUTE {PostgresIdentifier.Literal(sql)};");
                _writer.WriteLine("    EXCEPTION WHEN duplicate_object THEN NULL;");
                _writer.WriteLine("    END;");
                _writer.WriteLine("  END IF;");
                _writer.WriteLine("END");
                _writer.WriteLine("$mdb$;");
            }

            _writer.WriteLine();
        }
    }

    public int BatchSize => _batchSize;

    public void Dispose() => _writer.Flush();

    private static string CastType(ColumnSchema column)
    {
        if (column.IsAutoIncrement)
        {
            return column.PostgresType;
        }

        return column.PostgresType;
    }

    private static string BuildCreateTable(TableSchema table, bool ifNotExists)
    {
        var builder = new StringBuilder();
        builder.Append("CREATE TABLE ");
        if (ifNotExists)
        {
            builder.Append("IF NOT EXISTS ");
        }

        builder.Append(PostgresIdentifier.Quote(table.Name));
        builder.AppendLine(" (");

        var lines = new List<string>();
        foreach (var column in table.Columns)
        {
            var typeSql = ColumnTypeSql(column);
            var nullSql = column.AllowNull || column.IsAutoIncrement ? "" : " NOT NULL";
            lines.Add($"  {PostgresIdentifier.Quote(column.Name)} {typeSql}{nullSql}");
        }

        if (table.PrimaryKeyColumns.Count > 0)
        {
            var pk = string.Join(", ", table.PrimaryKeyColumns.Select(PostgresIdentifier.Quote));
            lines.Add($"  PRIMARY KEY ({pk})");
        }

        builder.AppendLine(string.Join("," + Environment.NewLine, lines));
        builder.Append(");");
        return builder.ToString();
    }

    private static string ColumnTypeSql(ColumnSchema column)
    {
        if (column.IsAutoIncrement)
        {
            return column.PostgresType + " GENERATED BY DEFAULT AS IDENTITY";
        }

        return column.PostgresType;
    }

    private void WriteIndexes(TableSchema table, bool guarded)
    {
        var used = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var index in table.Indexes)
        {
            if (index.IsPrimaryKey || index.Columns.Count == 0)
            {
                continue;
            }

            var indexName = string.IsNullOrWhiteSpace(index.Name)
                ? $"IX_{table.Name}_{string.Join("_", index.Columns)}"
                : index.Name;
            if (!used.Add(indexName))
            {
                indexName += "_" + used.Count.ToString(CultureInfo.InvariantCulture);
            }

            var unique = index.IsUnique ? "UNIQUE " : "";
            var ifNotExists = guarded ? "IF NOT EXISTS " : "";
            var sql =
                $"CREATE {unique}INDEX {ifNotExists}{PostgresIdentifier.Quote(indexName)} ON {PostgresIdentifier.Quote(table.Name)} " +
                $"({string.Join(", ", index.Columns.Select(PostgresIdentifier.Quote))})";

            if (!guarded)
            {
                _writer.WriteLine(sql + ";");
                continue;
            }

            _writer.WriteLine("DO $mdb$");
            _writer.WriteLine("BEGIN");
            _writer.WriteLine($"  IF EXISTS (SELECT 1 FROM {CreatedTable} WHERE name = {PostgresIdentifier.Literal(table.Name)}) THEN");
            _writer.WriteLine($"    EXECUTE {PostgresIdentifier.Literal(sql)};");
            _writer.WriteLine("  END IF;");
            _writer.WriteLine("END");
            _writer.WriteLine("$mdb$;");
        }
    }
}
